name: products_service
description: Products catalog microservice built with Dart Frog
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.2.6
  postgres: ^3.5.9

dev_dependencies:
  dart_frog_cli: ^1.2.14
  test: ^1.31.0
